// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTestimonial from '@/components/sections/about/AboutTestimonial';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about" data-webild-component="AboutTestimonial" data-webild-component-path="@/components/sections/about/AboutTestimonial">
            <SectionErrorBoundary name="about">
              <AboutTestimonial
        tag="Náš příběh"
        quote="Každý kousek od Makronky od holky je malé umělecké dílo, tvořené s opravdovou vášní, z prémiových surovin a s osobním přístupem, který udělá vaše oslavy skutečně výjimečnými."
        author="Cukrářka a zakladatelka"
        role="Majitelka studia"
        imageSrc="http://img.b2bpic.net/free-photo/retired-man-following-culinary-advice-tablet-learning-cooking-tutorial-social-media-forming-dough-with-wooden-rolling-pin-grandfather-with-bonete-apron-using-laptop-preparing-home-cakes_482257-14491.jpg"
        textAnimation="slide-up"
      />
            </SectionErrorBoundary>
          </div>
  );
}
