// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTestimonial from '@/components/sections/about/AboutTestimonial';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about" data-webild-component="AboutTestimonial" data-webild-component-path="@/components/sections/about/AboutTestimonial">
            <SectionErrorBoundary name="about">
              <AboutTestimonial
        tag="Náš příběh"
        quote="Každý kousek od Makronky od holky je malé umělecké dílo, tvořené s opravdovou vášní, z prémiových surovin a s osobním přístupem, který udělá vaše oslavy skutečně výjimečnými."
        author="Cukrářka a zakladatelka"
        role="Majitelka studia"
        imageSrc="https://storage.googleapis.com/webild/users/user_3DGTos4IdMkmcPKS7sAmVMjyyeJ/uploaded-1785345775072-7gf1949d.png"
        textAnimation="slide-up"
      />
            </SectionErrorBoundary>
          </div>
  );
}
