// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "cakes" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function CakesSection(): React.JSX.Element {
  return (
    <div id="cakes" data-section="cakes" data-webild-component="FeaturesImageBento" data-webild-component-path="@/components/sections/features/FeaturesImageBento">
            <SectionErrorBoundary name="cakes">
              <FeaturesImageBento
                tag="Dorty na míru a makronky
"
                title="Nezapomenutelné sladké okamžiky"
                description="Od několikapatrových svatebních dortů až po vyladěné makronky na míru – proměníme vaši představu ve skutečnost."
                items={[
                  { title: "Dorty na míru", description: "Originální design pro narozeniny i svatby", imageSrc: "http://img.b2bpic.net/free-photo/cupcake-still-life_23-2148097833.jpg" },
                  { title: "Ikonické makronky", description: "Svěží chutě v dokonalém provedení", imageSrc: "http://img.b2bpic.net/free-photo/web_53876-88496.jpg" },
                  { title: "", description: "", imageSrc: "http://img.b2bpic.net/free-photo/green-red-sweets-served-box-candy-bar_8353-8474.jpg" },
                  { title: "Tématické makronky", description: "Osobitý styl vytvořený přesně podle vás", imageSrc: "https://images.pexels.com/photos/16946899/pexels-photo-16946899.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=16946899" },
                  { title: "", description: "", imageSrc: "http://img.b2bpic.net/free-photo/tasty-morning-pastry-coffee-display-traditional-city-cafe_613910-18517.jpg" },
                  { title: "", description: "", imageSrc: "http://img.b2bpic.net/free-photo/slice-chocolate-cake-glass-plate_114579-87378.jpg" },
                  { title: "", description: "", imageSrc: "http://img.b2bpic.net/free-photo/pyramid-pink-white-macaroons_1304-5624.jpg" }
                ]}
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
