// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "cakes" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function CakesSection(): React.JSX.Element {
  return (
    <div id="cakes" data-section="cakes" data-webild-component="FeaturesImageBento" data-webild-component-path="@/components/sections/features/FeaturesImageBento">
            <SectionErrorBoundary name="cakes">
              <FeaturesImageBento
                tag="Custom Cakes & Sweet Bars"
                title="Unforgettable edible moments."
                description="From tiered wedding cakes to bespoke sweet bars, we bring your vision to life."
                items={[
                  { title: "Bespoke Cakes", description: "Custom birthday & wedding creations.", imageSrc: "http://img.b2bpic.net/free-photo/cupcake-still-life_23-2148097833.jpg" },
                  { title: "Signature Macarons", description: "Timeless flavors reimagined.", imageSrc: "http://img.b2bpic.net/free-photo/web_53876-88496.jpg" },
                  { title: "Full Sweet Bars", description: "Perfect for your event.", imageSrc: "http://img.b2bpic.net/free-photo/green-red-sweets-served-box-candy-bar_8353-8474.jpg" },
                  { title: "Themed Macarons", description: "Personalized for you.", imageSrc: "http://img.b2bpic.net/free-photo/chocolate-cookies-glass-cup-top-view_114579-19093.jpg" },
                  { title: "Artisan Pastry", description: "Small-batch delights.", imageSrc: "http://img.b2bpic.net/free-photo/tasty-morning-pastry-coffee-display-traditional-city-cafe_613910-18517.jpg" },
                  { title: "Gourmet Cakes", description: "Artistry in every slice.", imageSrc: "http://img.b2bpic.net/free-photo/slice-chocolate-cake-glass-plate_114579-87378.jpg" },
                  { title: "Sladká svatba
 Desserts", description: "Sweet dreams come true.", imageSrc: "http://img.b2bpic.net/free-photo/pyramid-pink-white-macaroons_1304-5624.jpg" }
                ]}
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
