// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact" data-webild-component="ContactCta" data-webild-component-path="@/components/sections/contact/ContactCta">
            <SectionErrorBoundary name="contact">
              <ContactCta
                tag="Get in Touch"
                text="Ready to craft something beautiful together? Let's discuss your custom order today."
                primaryButton={{ text: "Contact Us", href: "mailto:hello@makronkyodholky.cz" }}
                secondaryButton={{ text: "Visit Our Instagram", href: "https://instagram.com" }}
                textAnimation="fade-blur"
              />
            </SectionErrorBoundary>
          </div>
  );
}
