// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact" data-webild-component="ContactCta" data-webild-component-path="@/components/sections/contact/ContactCta">
            <SectionErrorBoundary name="contact">
              <ContactCta
                tag="Ozvěte se nám!"
                text="Chcete společně vytvořit něco krásného? Pojďme ještě dnes probrat vaši zakázku na míru."
                primaryButton={{ text: "Kontaktujte nás", href: "mailto:hello@makronkyodholky.cz" }}
                secondaryButton={{ text: "Navštivte náš Instagram", href: "https://instagram.com" }}
                textAnimation="fade-blur"
              />
            </SectionErrorBoundary>
          </div>
  );
}
