// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBillboard from '@/components/sections/hero/HeroBillboard';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero" data-webild-component="HeroBillboard" data-webild-component-path="@/components/sections/hero/HeroBillboard">
            <SectionErrorBoundary name="hero">
              <HeroBillboard
                tag="Kutná Hora, Czech Republic"
                title="Handmade sweetness, made just for you."
                description="Beautiful handmade macarons, cakes, and custom sweet creations crafted in Kutná Hora."
                primaryButton={{ text: "Request an Order", href: "#contact" }}
                secondaryButton={{ text: "Explore Our Creations", href: "#macarons" }}
                imageSrc="http://img.b2bpic.net/free-photo/abstract-minimal-concept-veggies-plate-copy-space_23-2148835310.jpg"
                textAnimation="fade-blur"
              />
            </SectionErrorBoundary>
          </div>
  );
}
