// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "macarons" section.

import React from 'react';
import FeaturesBento from '@/components/sections/features/FeaturesBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MacaronsSection(): React.JSX.Element {
  return (
    <div id="macarons" data-section="macarons" data-webild-component="FeaturesBento" data-webild-component-path="@/components/sections/features/FeaturesBento">
            <SectionErrorBoundary name="macarons">
              <FeaturesBento
                tag="Our Specialties"
                title="The star of the show: macarons."
                description="Handmade macarons are at the heart of our studio. From timeless classics like Pistachio and Salted Caramel to playful custom themes for your special events."
                features={[
                  {
                    title: "Artisanal Craft",                description: "Every batch is handcrafted to ensure the perfect texture and vibrant flavor.",                bentoComponent: "media-stack",                mediaItems: [
                      { imageSrc: "http://img.b2bpic.net/free-photo/top-view-delicious-french-macarons-with-candies-inside-tray-dark-space_140725-97872.jpg" },
                      { imageSrc: "http://img.b2bpic.net/free-photo/delicious-cookies-arrangement_23-2150714538.jpg" },
                      { imageSrc: "http://img.b2bpic.net/free-photo/top-view-colorful-delicious-macarons-little-cakes-with-candies-white-space_140725-79670.jpg" }
                    ]
                  },
                  {
                    title: "Custom Themes",                description: "Personalized designs for weddings, birthdays, and corporate branding.",                bentoComponent: "checklist-timeline",                heading: "Design Process",                subheading: "From concept to creation",                checklistItems: [
                      { label: "Flavor Selection", detail: "Consultation" },
                      { label: "Visual Design", detail: "Custom palette" },
                      { label: "Hand-finishing", detail: "Detailing" }
                    ],
                    completedLabel: "Ready"
                  }
                ]}
                textAnimation="fade"
              />
            </SectionErrorBoundary>
          </div>
  );
}
