// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "macarons" section.

import React from 'react';
import FeaturesBento from '@/components/sections/features/FeaturesBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MacaronsSection(): React.JSX.Element {
  return (
    <div id="macarons" data-section="macarons" data-webild-component="FeaturesBento" data-webild-component-path="@/components/sections/features/FeaturesBento">
            <SectionErrorBoundary name="macarons">
              <FeaturesBento
        tag="Naše specialita"
        title="Makronky jsou naše srdcovka."
        description="Makronky jsou hlavní specialitou Makronky od holky. Od nadčasových příchutí až po hravé tematické výtvory, každá makronka je pečlivě vyrobena s důrazem na chuť, texturu, barvu a detail."
        features={[{"description":"Pistácie, Malina, Slaný karamel a další oblíbené příchutě.","mediaItems":[{"imageSrc":"https://images.unsplash.com/photo-1569864358642-9d1684040f43?q=80&w=2940&auto=format&fit=crop"},{"imageSrc":"https://images.unsplash.com/photo-1558326567-98ae2405596b?q=80&w=2859&auto=format&fit=crop"},{"imageSrc":"https://images.unsplash.com/photo-1571115177098-24ec42ed204d?q=80&w=2787&auto=format&fit=crop"}],"bentoComponent":"media-stack","title":"Oblíbené příchutě"},{"title":"Tematické makronky","description":"Personalizované designy pro svatby, narozeniny a firemní akce.","bentoComponent":"checklist-timeline","completedLabel":"Hotovo","checklistItems":[{"detail":"Konzultace","label":"Výběr příchutí"},{"detail":"Vlastní paleta","label":"Vizuální design"},{"detail":"Zdobení","label":"Ruční dokončení"}],"subheading":"Od konceptu k realizaci","heading":"Proces tvorby"}]}
        textAnimation="fade"
        primaryButton={{"text":"Chci objednat makronky","href":"#contact"}}
      />
            </SectionErrorBoundary>
          </div>
  );
}
