// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "pricing" section.

import React from 'react';
import PricingSimpleCards from '@/components/sections/pricing/PricingSimpleCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function PricingSection(): React.JSX.Element {
  return (
    <div id="pricing" data-section="pricing" data-webild-component="PricingSimpleCards" data-webild-component-path="@/components/sections/pricing/PricingSimpleCards">
            <SectionErrorBoundary name="pricing">
              <PricingSimpleCards
                tag="Nezávažně poptat
"
                title="Začněte svou sladkou cestu."
                description="Každou objednávku tvoříme s péčí a na míru vašemu přání, příležitosti i počtu hostů. Napište nám svou představu a společně vytvoříme něco opravdu výjimečného."
                plans={[
                  { tag: "Pro malé oslavy
", price: "Custom", description: "Small-batch orders & themed boxes.", features: ["Consultation", "1 Flavor Choice", "Pick-up in KH"] },
                  { tag: "Pro velké oslavy", price: "Custom", description: "Large events & sweet bars.", features: ["Full Design", "Multiple Flavors", "Delivery Option"] },
                  { tag: "Wedding", price: "Custom", description: "Premium full-scale service.", features: ["Design Suite", "Custom Palette", "Set-up Service"] }
                ]}
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
