// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "pricing" section.

import React from 'react';
import PricingSimpleCards from '@/components/sections/pricing/PricingSimpleCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function PricingSection(): React.JSX.Element {
  return (
    <div id="pricing" data-section="pricing" data-webild-component="PricingSimpleCards" data-webild-component-path="@/components/sections/pricing/PricingSimpleCards">
            <SectionErrorBoundary name="pricing">
              <PricingSimpleCards
                tag="Nezávažně poptat
"
                title="Začněte svou sladkou cestu."
                description="Každou objednávku tvoříme s péčí a na míru vašemu přání, příležitosti i počtu hostů. Napište nám svou představu a společně vytvoříme něco opravdu výjimečného."
                plans={[
                  { tag: "Základní", price: "Sladké okamžiky", description: "Ideální volba pro menší oslavy, tematické krabičky a chvíle, které si zaslouží něco sladkého.", features: ["Osobní konzultace", "Výběr příchutí podle nabídky", "Pečlivě připravená objednávka"] },
                  { tag: "Oslavy", price: "Sladké okamžiky", description: "Proměníme vaši oslavu v nezapomenutelný zážitek.", features: ["Tvorba na míru vašemu přání", "Výběr z více příchutí", "Sladké pohoštění pro vaše hosty"] },
                  { tag: "Wedding", price: "Sladké okamžiky", description: "Elegantní sladké pohoštění vytvořené pro jeden z nejdůležitějších dnů vašeho života.", features: ["Individuální návrh", "Sladké okamžiky Palette", "Komplexní sladké pohoštění"] }
                ]}
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
