// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialTrustCard from '@/components/sections/testimonial/TestimonialTrustCard';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials" data-webild-component="TestimonialTrustCard" data-webild-component-path="@/components/sections/testimonial/TestimonialTrustCard">
            <SectionErrorBoundary name="testimonials">
              <TestimonialTrustCard
                quote="The macarons were not only stunning to look at, but they tasted like heaven. A true centerpiece for our wedding celebration!"
                rating={5}
                author="Jana Novotná"
                avatars={[
                  { name: "Jana", imageSrc: "http://img.b2bpic.net/free-photo/female-confectioner-boxing-desserts_23-2150360238.jpg" },
                  { name: "Petr", imageSrc: "http://img.b2bpic.net/free-photo/portrait-smiling-young-woman-wearing-coat_171337-17061.jpg" },
                  { name: "Lucie", imageSrc: "http://img.b2bpic.net/free-photo/stylish-young-girl-student-curly-dark-hair-looking-with-anticipation-interest-smiling-pleased-gazing-camera-waiting-hopeful-white-background_176420-46707.jpg" },
                  { name: "David", imageSrc: "http://img.b2bpic.net/free-photo/online-doctor-clinic-young-woman-medical-face-mask-using-smartphone-client-remote-online_1258-118496.jpg" },
                  { name: "Klára", imageSrc: "http://img.b2bpic.net/free-photo/serious-young-lady-posing-while-sitting-near-cupcakes_171337-14482.jpg" }
                ]}
                textAnimation="fade"
              />
            </SectionErrorBoundary>
          </div>
  );
}
